---
abstract: "\"Higher Order Perl\" Parser"
author:
  - 'Mark Jason Dominus <mjd@plover.com>'
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
  - 'David E. Wheeler <david@justatheory.com>'
  - 'Xavier Caron <xav@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HOP-Parser
no_index:
  directory:
    - t
    - inc
requires:
  HOP::Lexer: 0.032
  HOP::Stream: 0.03
  Sub::Uplevel: 0
resources:
  homepage: http://hop.perl.plover.com/
  x_MailingList: http://hop.perl.plover.com/#mlist
version: 0.02_04
